-- Migration 007 intentionally retired as a NO-OP.
--
-- The Product Identity cloud schema originally prepared under this version
-- was never deployed to production and is not required for receipt cloud
-- backup/restore.
--
-- The prepared schema is preserved at:
-- supabase/prepared/product_identity_entities.sql
--
-- Keep this migration version as a no-op so migration history remains ordered.
SELECT 1;
